# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 534ea8efe31cdf5c9ba01c71e37e699af81c858540b83b058980f98db46fa9f2c5427cbfb51d699cd713ee62c5f53ec58b0d2c73e260e6fbda604416845586af

test:
  secret_key_base: b9f8cc6a910aa87902bb02e7e9c58fd60886c622472c5c540d44bfebf6de88c17e31163c46bbdceb177c2780db1c8a5ab0e4aad97b7f566b7d5823cf5868581b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
